vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        events_images:
            uri_prefix: /images/events
            upload_destination: oneup_flysystem.events_images_filesystem
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
