vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        events_images:
            uri_prefix: /images/events
            upload_destination: oneup_flysystem.events_images_filesystem
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        boilers_images:
            uri_prefix: /images/boilers
            upload_destination: oneup_flysystem.boilers_images_filesystem
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        works_plans:
            uri_prefix: /images/plans
            upload_destination: oneup_flysystem.works_plans_filesystem
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
