version: "3"

services:

    apache:
        build: docker/apache/
        ports: [ "80" ]
        volumes:
            - .:/var/www/html
        networks:
            - backend
        depends_on:
            - php

    php:
        build: docker/php/
        volumes:
            - $PWD:/var/www/html
        networks:
            - backend
        depends_on:
            - mysql

    mysql:
        build: docker/mysql/
        command:
            - --default-authentication-plugin=mysql_native_password
            - --sql-mode=ALLOW_INVALID_DATES
        ports: [ "3306" ]
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: general
        volumes:
            - mysql:/var/lib/mysql
            - ./docker/mysql/data:/docker-entrypoint-initdb.d
        networks:
            - backend
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports: [ 80 ]
        environment:
            PMA_HOST: "mysql"
            PMA_PORT: "3306"
            PMA_USER: "root"
            PMA_PASSWORD: "root"
        depends_on:
            - mysql
        networks:
            - backend

networks:
    backend:
        external: true

volumes:
    mysql: ~
